### ISSUE TITLE
replace force_unicode to force_text for django >=1.6 in widgets.py

### ISSUE THREAD

**Issue by ghost** [riklaunim/django-ckeditor#1]

**Comment by riklaunim** [comment]
Will check that out. Is there a difference for 1.4-1.5?

**Comment by ghost** [comment]
I can't use 1.6 with Python 3.3 without it. 

https://docs.djangoproject.com/en/dev/topics/python3/#string-handling

try import force_text (Django1.6+), or use force_unicode as force_text (Django<1.6) on ImportError exception.

**Comment by riklaunim** [comment]
Ok, will fix that.
