### ISSUE TITLE
Fetching Media from CKEditor Upload Path

### ISSUE THREAD

**Issue by radzhome** [riklaunim/django-ckeditor#12]
Here are my settings, and note it does not matter if i specify CKEDITOR_UPLOAD_PREFIX in my settings or not, it loads the entire absolute path on the server side when trying to load the image instead of going to /media/ckeditor_uploads/... it uses /var/web/project_env/project_name/media ... which is the CKEDITOR_UPLOAD_PATH not the media url!  This bug only exists in django 1.6 / python 3.3 when I tried with django 1.5.5 and python 2.7.3 it was fine..
# CK Editor

CKEDITOR_UPLOAD_PATH = os.path.join(MEDIA_ROOT, "ckeditor_uploads")

CKEDITOR_UPLOAD_PREFIX = os.path.join(MEDIA_URL, "ckeditor_uploads")

**Comment by radzhome** [comment]
There is something wrong with the get_media_url function in views , it does not return the correct media url, it uses the path it receives for me, which is what is happening on the site...

> > > from ckeditor import views
> > > views.get_media_url('/Users/CLDSupportSystems/python3_env/clearcms/media/ckeditor_uploads/2013/12/06/images.jpg')
> > > '/Users/CLDSupportSystems/python3_env/clearcms/media/ckeditor_uploads/2013/12/06/images.jpg'

**Comment by radzhome** [comment]
Python is 3.3.2 btw, 
Python 3.3.2 (default, Nov 27 2013, 19:25:59) 
[GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.2.79)] on darwin

I'll investigate more.

**Comment by riklaunim** [comment]
get_media_url is a direct wrapper around django default storage.

**Comment by radzhome** [comment]
Yeah i see that. I wonder what will happen if I define DEFAULT_FILE_STORAGE in my settings. You know how to see what the default_storage is equal to ? 

> > > from django.core.files.storage import default_storage
> > > default_storage
> > > <django.core.files.storage.DefaultStorage object at 0x103d3ed10>

**Comment by radzhome** [comment]
> > > default_storage.location
> > > '/Users/CLDSupportSystems/python3_env/clearcms/media'

Yeah so default storage is returning the correct info, but this isn't the url

**Comment by riklaunim** [comment]
default storage by default is the plain file system storage. I'm planning to add a set of tests managed by tox so it will be easy to compare tests for Py 3.3 and for example 2.7 or different django versions.

**Comment by radzhome** [comment]
Something is broken in default_storage.url() , see for yourself:

> > > default_storage.url('/Users/CLDSupportSystems/python3_env/clearcms/media/ckeditor_uploads/2013/12/06/images.jpg')
> > > '/Users/CLDSupportSystems/python3_env/clearcms/media/ckeditor_uploads/2013/12/06/images.jpg'
> > > 
> > > from clearcms.settings import MEDIA_URL
> > > MEDIA_URL
> > > '/media/'
> > > from clearcms.settings import MEDIA_ROOT
> > > MEDIA_ROOT
> > > '/Users/CLDSupportSystems/python3_env/clearcms/media'
> > > from clearcms.settings import CKEDITOR_UPLOAD_PATH
> > > CKEDITOR_UPLOAD_PATH
> > > '/Users/CLDSupportSystems/python3_env/clearcms/media/ckeditor_uploads'
> > > from clearcms.settings import CKEDITOR_UPLOAD_PREFIX
> > > CKEDITOR_UPLOAD_PREFIX
> > > '/media/ckeditor_uploads'

Are you from Poland?

**Comment by radzhome** [comment]
My Bad, this works, I was using the full path but that's what it seems to be doing.  the path submitted in 

> > > default_storage.url('ckeditor_uploads/2013/12/06/images.jpg')
> > > '/media/ckeditor_uploads/2013/12/06/images.jpg'
> > > 
> > > saved_path = default_storage.save('text.txt', ContentFile('new content'))
> > > saved_path
> > > 'text.txt'

This works too.. I'll have to add a logger to this and run the server and see what it prints for some of these values

**Comment by radzhome** [comment]
On the server side the upload goes through just fine, but the url is all wrong

img src="/Users/CLDSupportSystems/python3_env/clearcms/media/ckeditor_uploads/2013/12/06/images_thumb.jpeg">

**Comment by riklaunim** [comment]
I'm from Poland. There may be a bug somewhere - even in Django. I'll add a demo app and tox so it would be easier to test/debug.

**Comment by radzhome** [comment]
Juz dawno mnie tam nie bylo (3 lata)! haha

So my debug code shows that the returned save_path is not relative to the static_root , its the full path which is the culprit:

INFO at get media url, path: /Users/CLDSupportSystems/python3_env/clearcms/media/ckeditor_uploads/2013/12/06/images_thumb.jpeg
INFO at get media url, path: /Users/CLDSupportSystems/python3_env/clearcms/media/ckeditor_uploads/2013/12/06/images.jpeg
INFO going in at upload
INFO saved path: /Users/CLDSupportSystems/python3_env/clearcms/media/ckeditor_uploads/2013/12/06/images_1.jpeg
INFO at get media url, path: /Users/CLDSupportSystems/python3_env/clearcms/media/ckeditor_uploads/2013/12/06/images_1.jpeg
INFO url to saved path: /Users/CLDSupportSystems/python3_env/clearcms/media/ckeditor_uploads/2013/12/06/images_1.jpeg

I need a better tool to step through code as I run the server. I use django-extensions runserver_plus . What is best django debug toolbar?

**Comment by radzhome** [comment]
in ckeditor.views.upload I have uplaod_file_name  equal to the entire path to the file instead of media_root : 

INFO upload_file_name: /Users/CLDSupportSystems/python3_env/clearcms/media/ckeditor_uploads/2013/12/06/images_2.jpeg

# this should be ckeditor_uploads/2013/12/06/images_2.jpeg

**Comment by radzhome** [comment]
Dropped to django 1.5.5 but still same problem, I think i'll port this app to python 2.7.x because it worked.  This project is prolly not fully python 3 ready, I see a lot of unicode definitions.  Starting a Python 3 project is probably a bad idea.. too early

**Comment by riklaunim** [comment]
There is at least one other Python 3.3 user out there. When I'll add the tox/test set then you could run it to compare results for two Python versions. If there is a bug we have to find it.

**Comment by radzhome** [comment]
Oh i don't see CKEDITOR_UPLOAD_PREFIX anywhere in the code  this is a poor name but really its the MEDIA_URL for ckeditor upload, should be named CKEDITOR_UPLOAD_URL or something but whatever.  I can paste what I did momentarily but will need testing

**Comment by riklaunim** [comment]
There is only CKEDITOR_UPLOAD_PATH, which should be just a relative path against MEDIA_ROOT (for a file system storage).

**Comment by radzhome** [comment]
Adding this to get_media_url fixes the problem, sort of, but the thumb isn't uploading

```
media_root = getattr(settings, 'MEDIA_ROOT', False)
path = os.path.relpath(path, start=media_root)
```

plus this is a hack because it assumes that your media url and media root are 'path/to/media' and 'media' respectively.

**Comment by radzhome** [comment]
The thumbnail is a separate problem, the generated thumb is 0kb in size.

**Comment by riklaunim** [comment]
that bug is already known, I strigified an object. I'm setting up some integration tests so you will be able to run them in your env.

**Comment by radzhome** [comment]
Its putting <_io.StringIO object at 0x107d74120>  String IO Objects inside the root. First of all this should be changd to ByteIO (more appropriate). 

I think its an easy fix though, would have to look through this PIL code and compare it to mine that works nicely for the python 3 cms I wrote, here it is (on save):

```
    from PIL import Image
        from PIL import ImageOps
        from io import BytesIO
        from django.core.files.uploadedfile import SimpleUploadedFile

        THUMBNAIL_RATIO = 1.1875  # ratio used to get width based on height
        MAX_LW = 360  # 1024  # max width or height
        MIN_LW = 320  # min width or height

        image_new = BytesIO(self.photo.read())  # reads in photo into buffer

        image = Image.open(image_new)  # orig. image , will not touch this, messing w/ imagefit only
        if image.mode not in ('L', 'RGB'):
            image = image.convert('RGB')
        w, h = image.size

        if w > MAX_LW or h > MAX_LW:  # ensures photo wont be too big, no need to make them too large
            h = MAX_LW
        if w < MIN_LW or h < MIN_LW:  # ensures photo wont be too small, will strech it
            h = MIN_LW

        w = h * THUMBNAIL_RATIO  # will keep original width, but resize

        # now can do all the operations
        imagefit = ImageOps.fit(image, (int(w), int(h)), Image.ANTIALIAS)  # crops the image down

        temp_handle = BytesIO()  # temp buffer to write file to
        imagefit.save(temp_handle, 'png')  # image stored to stringIO,  temp buffer as png
        temp_handle.seek(0)  # sets position of file to 0,, for reading by simple file uploader
        suf = SimpleUploadedFile(os.path.split(self.photo.name)[-1],   # Save to the thumbnail field
                                 temp_handle.read(), content_type='image/png')  # reads in the file to save it
```

super(Photo, self).save()

This works great but in reality I'm still going to port to Python 2 using six because I see most of the packages I want to add only support 2.x

**Comment by radzhome** [comment]
wyslij mi emaila na radzhome na gmail, chcialem porozmawiac

**Comment by riklaunim** [comment]
poszło ;)

**Comment by riklaunim** [comment]
CKEDITOR_UPLOAD_PATH should be relative.

**Comment by radzhome** [comment]
:) W nastepny rok musze sie uzywac pypi , to wzuce moje apps na to :)
