### ISSUE TITLE
MANIFEST.in not honoured during install phase

### ISSUE THREAD

**Issue by ghost** [riklaunim/django-ckeditor#14]
When installing django-ckeditor-updated from Pypi, static files and templates do not get copied to the installation directory.

If I switch to setuptools and enable `include_package_data=True` then all the assets get copied as expected.

``` diff
diff --git a/setup.py b/setup.py
index 9f97b2c..9e7c08f 100644
--- a/setup.py
+++ b/setup.py
@@ -1,5 +1,5 @@
 import os.path
-from distutils.core import setup
+from setuptools import setup


 def get_source_files():
@@ -32,4 +32,5 @@ setup(
         "Intended Audience :: Developers",
         "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
     ],
+    include_package_data=True,
 )
```

I could not see what is wrong with your current setup.py though. After reading distutils docs it seems fine but here with Python 3.3 it really doesn't install all required files.

**Comment by riklaunim** [comment]
I'll look into this, and quite likely switch.

**Comment by ghost** [comment]
Wow amazing reactivity! Thanks! It's really cool that your maintaining this app alive. Was pleasantly surprised with the file upload functionality. Together with contrib.flatpages it makes a pretty decent minimal CMS.
