### ISSUE TITLE
image and management missing from pypi package

### ISSUE THREAD

**Issue by ZAlfonse** [riklaunim/django-ckeditor#15]
I might be really stupid here, but the version on pypi doesn't include the image or management packages.

**Comment by ngenator** [comment]
Need to be added to the `setup.py`

Instead of 

```
packages=[
    'ckeditor',
],
```

should use 

```
from setuptools import setup, find_packages
...
packages=find_packages(exclude=["*.demo"]),
```

http://pythonhosted.org/setuptools/setuptools.html#using-find-packages
