### ISSUE TITLE
Bad Request on file upload

### ISSUE THREAD

**Issue by jnns** [riklaunim/django-ckeditor#23]
Browsing the media gallery or uploading a new image results in a server error 
**400 Bad Request**.

I'm guessing this is a configuration error as it worked before and I just upgraded to django-ckeditor-updated on the production server but as of yet I don't know what causes this. As soon as I find out, we should improve the error handling.

**Comment by riklaunim** [comment]
Configuration is different than in django-ckeditor. The upload path is now relative to MEDIA_ROOT thanks to django filestorage usage. If you have the old absolute path it will be "blocked" - probably by the exception above (I would also expect "Suspicious Operation" etc.)

**Comment by jnns** [comment]
Thanks Piotr; that was it. Although I was aware of the config changes, I somehow managed to not commit the new settings. I feel dumb.
