### ISSUE TITLE
Same id field confusion

### ISSUE THREAD

**Issue by kuyucakli** [riklaunim/django-ckeditor#26]
I have to use two model form on the same page. And both models  have a description field with id_description... I want the second model form's description field to have ckeditor but it wraps the first one ... Can there be a solution on this?

**Comment by riklaunim** [comment]
You could try adding it a custom class and using that to enable ckeditor widget. Some customization may be needed.

**Comment by kuyucakli** [comment]
Thank you, i have found  ---->  customForm(auto_id='id_for_%s')   auto_id option when initializing a form so unique id can be set :)
