### ISSUE TITLE
Slugify unicode filenames

### ISSUE THREAD

**Issue by seedofjoy** [riklaunim/django-ckeditor#30]
Django slugify cuts all non-ascii letters, so if filename for example "изображение.jpg" - it throws exception in pillow_backend on `python thumbnail_format = utils.get_image_format(os.path.splitext(file_path)[1])`, because filename is empty.
I propose to use package trans (https://github.com/zzzsochi/trans) for this.
Method slugify_filename could be:

``` python
def slugify_filename(filename):
    u""" Slugify filename """
    name, ext = os.path.splitext(filename)
    import trans
    name = unicode(name).encode('trans/slug')
    return name + ext
```

If you do not mind about adding additional dependencies, I could create a pull request for this.

**Comment by riklaunim** [comment]
If the package is well maintained, works on Py 3.3 and with latest Django versions then I see no problem :)
