### ISSUE TITLE
pastes html tags in wysiwyg

### ISSUE THREAD

**Issue by foreigner92** [riklaunim/django-ckeditor#34]
http://stackoverflow.com/questions/22043903/django-ckeditor-pastes-html-tags-in-wysiwyg

**Comment by riklaunim** [comment]
and answered :)

**Comment by dimitrisr** [comment]
I am facing kind of a similar issue, when I type greek (or any other language with special characters) in the editor. It automatically changes the text to "&Eta; &pi;&alpha;&rho;έ&lambda;&alpha;&sigma;&eta; &mu;&epsilon; ". I found in a documentation that I have to use 
'config.entities' : False,
'config.entities_latin' : False,
'config.entities_greek' : False,
to fix it, but it didn't help. Is there anything else I need to be doing?

**Comment by riklaunim** [comment]
I don't know. I'll look at it today before version bumping. ckeditor version also got updated, maybe that will help too. If it happens after saving entry in the database then some backend issues may cause this.

**Comment by dimitrisr** [comment]
riklaunim, it happens as soon as I type/paste the text in the editor, and switch to code view.

**Comment by riklaunim** [comment]
This seems to work:

```
CKEDITOR_CONFIGS = {
    'default': {
        'entities': False,
        'entities_latin': False,
        'entities_greek': False,
    }
}
```

**Comment by dimitrisr** [comment]
Many thanks riklaunim! I had inserted wrong the configuration options. It does work now.
