### ISSUE TITLE
How to config protectedSource for placeholders

### ISSUE THREAD

**Issue by alexander-arce** [riklaunim/django-ckeditor#37]
Whats is the way to config django-ckeditor for 'protect'  django placeholders on templates
edited with CKEditor.
###### Example:

protectedSource.push(/{%[\s\S]*?\%}/g) thus protect placeholders like :
- {% for item in items %}
- {% endfor %}

**Comment by riklaunim** [comment]
You may have to add such part to your own JS file.

**Comment by alexander-arce** [comment]
@riklaunim you overtake me for a one minute.
Im add my own **ckeditor_config.js with 

> CKEDITOR.editorConfig = function( config ) {
>    config.protectedSource.push(/{%[\s\S]_?\%}/g);
>    config.protectedSource.push(/{{[\s\S]_?}}/g);
> };

and add reference on 

> CKEDITOR_CONFIGS = {
> ...
> 'customConfig': 'ckeditor_config.js',
> ...
> }

Best regards.
