### ISSUE TITLE
ckeditor image upload gives 400 bad request

### ISSUE THREAD

**Issue by kuyucakli** [riklaunim/django-ckeditor#39]
Hi i have set:

CKEDITOR_UPLOAD_PATH = normpath(join(DJANGO_ROOT, '/uploads'))
CKEDITOR_UPLOAD_PREFIX = '/uploads/'
CKEDITOR_MEDIA_PREFIX = '/uploads'

But i get bad request error 400

i have checked inspector and request path is http://127.0.0.1:8000/ckeditor/upload/?CKEditor=id_description&CKEditorFuncNum=34&langCode=en     it is not using http://127.0.0.1:8000/uploads/

**Comment by riklaunim** [comment]
do not use absolute paths. they are invalid from a long time ;)

Set CKEDITOR_UPLOAD_PATH to a relative path - a path relative to MEDIA_ROOT to which images will be uploaded.

```
CKEDITOR_UPLOAD_PATH = "uploads/"
```

**Comment by kuyucakli** [comment]
Thank you now it uploads but can not find the file to show:  Because it uses this path http://127.0.0.1:8000/Users/burakk/BurakWorks/Web/VIRTUAL_ENVIRONMENTS/django_python3.3/django_kuyu_web/django_kuyu_web/uploads/2014/05/29/1_650_4.jpg   ---> but it must be /uploads/2014/05/29/1_650_4.jpg

**Comment by riklaunim** [comment]
something still not right with the path settings
