### ISSUE TITLE
set full feature

### ISSUE THREAD

**Issue by ali-hallaji** [riklaunim/django-ckeditor#40]
Hi,
How to full feature my toolbar?
I need to justify alignment and pre tag for syntax highlighter.
please help me.
thanks

**Comment by riklaunim** [comment]
look at ckeditor config for it and then map it to the Python dictionary that django-ckeditor uses.

**Comment by ali-hallaji** [comment]
thank you for reply.
but don't corrected!
I use of django-ckeditor-updated.
Can you give me config for full feature toolbar in django settings here?

**Comment by riklaunim** [comment]
```
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Full',
        'height': 300,
        'width': 300,
    },
}
```

This is the full config.

**Comment by ali-hallaji** [comment]
No,/
I tested this config,but I don't see justify button or flash or copy to word or direction...
this is not work!

**Comment by riklaunim** [comment]
Then look into ckeditor documentation on how to enable them. This "default" config maps to what will be passed to the ckeditor instance. I didn't used all the fancy ckeditor features ;)

**Comment by ali-hallaji** [comment]
please say to me how to add pre,direction,justify?
These not in my toolbar

**Comment by paolodina** [comment]
Hello, I have a similar problem as the OP. This is my configuration in `settings.py`:

``` python
CKEDITOR_CONFIGS = {
    None: {
        'toolbar': [
            [ 'Link','Unlink' ],
            [ 'Image','Table','HorizontalRule','SpecialChar','-','SpellChecker' ],
            [ 'Source','About','InsertSnippet','BGColor','SimpleLink', 'Select', 'SelectToText', 'SelectorUpdateSelector','SimpleLink' ],
            [ 'Format','Font','FontSize' ],
            [ 'TextColor' ],
            [ 'Bold','Italic','Underline','Strike','Subscript','Superscript','-','RemoveFormat' ],
            [ 'NumberedList','BulletedList','-','Outdent','Indent','-','Blockquote','-','JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock' ],
        ]
    },
}
```

Everything works perfectly with the editor, but the only tools I see are:
- Link, Unlink - OK
- Image, Table, Insert Horizontal Line, Insert Special Character. **Missing:** separator, spell checker.
- Source, About. **Missing:** insert snippet, bgcolor, simple link, select, select to text
- Paragraph Format. **Missing**: font, font size
- **Missing**: text color
- Bold, Italic, Strike, Remove Format. **Missing**: Underline, Subscript, Superscript, separator
- Numbered list, Bullet list, Decrease indent, Increase Indent, Block quote **Missing:** Justify left, Justify center, Justify right, Justify block, separators

I used the same naming shown in [ckeditor example](http://nightly.ckeditor.com/14-07-02-06-05/standard/samples/plugins/toolbar/toolbar.html#currentToolbar).

Any hint greatly appreciated.

**Comment by josecostamartins** [comment]
So, i've manage to get textcolor and bgcolor running.
I had to download the colorbutton (http://ckeditor.com/addon/colorbutton) addon, and place it inside <many_folders>/ckeditor/plugins and in my settings i placed the following configuration:

``` python
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': None,
        'extraPlugins': 'colorbutton'
    },
}
```

Edit:
I believe the best way to package this app is to use ckeditor full preset option; and if somebody needs something more, he should fork, modify and then install directly from his "personal" fork on github.

what do you guys think?

**Comment by riklaunim** [comment]
I've switched from standard to full package which has colorbutton and other plugins. Should solve few similar cases.
