### ISSUE TITLE
look up uploaded image

### ISSUE THREAD

**Issue by rhinoxi** [riklaunim/django-ckeditor#41]
Hi riklaunim,
I got a problem in scanning server to look up the uploaded image.
If login as superuser, then no problem. All uploaded images were shown.
If login as non-superuser, then no images were found.
I checked the source file, ckeditor/views.py
and changed the line 96:
    directory_path = os.path.join(path, directory)
to:
    directory_path = os.path.join(user_path, path, directory)

and the problem seems to be solved.
But I don't know whether it will cause any other errors.

Thank you!

**Comment by riklaunim** [comment]
all uploads are made to project site media folder, into CKEDITOR_UPLOAD_PATH subfolder.

**Comment by rhinoxi** [comment]
I set CKEDITOR_RESTRICT_BY_USER = True, so the images are seperated by username, and the problem above appears.

**Comment by sylvain-josserand** [comment]
Should you put "if CKEDITOR_RESTRICT_BY_USER:" just before line 96? So that
would look like:

if CKEDITOR_RESTRICT_BY_USER:
    directory_path = os.path.join(user_path, path, directory)
else:
    directory_path = os.path.join(path, directory)

Am i right?

**Comment by riklaunim** [comment]
looks like so. Will have to check that, add a test or two :)

**Comment by riklaunim** [comment]
I've checked the code and everything seems to be working correctly. At ckeditor/views.py line 96 there is a try/except statement so you must have been looking on one of older versions.
