### ISSUE TITLE
stylesheetparser was not found

### ISSUE THREAD

**Issue by kuyucakli** [riklaunim/django-ckeditor#42]
I get  error -> 
Resource name "stylesheetparser" was not found at "http://www.minimizma.com/static/ckeditor/ckeditor/plugins/stylesheetparser/plugin.js?t=E4K

not locally but on the far server?

**Comment by riklaunim** [comment]
Should be fixed by bc03b828cbea7ca209fcbb25c23d7de756949e78 - using a full package and not "standard" which lacks some plugins/files.

**Comment by kuyucakli** [comment]
How will i load it via pip?

**Comment by riklaunim** [comment]
use newer version of the package, that's all.

**Comment by kuyucakli** [comment]
Sorry for my ignorance but what is this package thing? Will i use the master branch? Has master branch the full package?

**Comment by riklaunim** [comment]
django-ckeditor-4.4.5 as well as django-ckeditor-updated-4.4.4 have all the fixes.

**Comment by kuyucakli** [comment]
I can not find them among the branches :(

**Comment by kuyucakli** [comment]
ok pypi  version...

**Comment by kuyucakli** [comment]
I have upgraded via pip but now ckeditor does not work. I get no css or any other error?

**Comment by riklaunim** [comment]
Read the changelog, you need to give a CKEDITOR_JQUERY_URL.

JS console would told you something is wrong. Try to debug problems more ;)

**Comment by riklaunim** [comment]
If you ommit the CKEDITOR_JQUERY_URL then it will use the grappeli jQuery. Also be sure to do collectstatic.
