### ISSUE TITLE
How to install plugins

### ISSUE THREAD

**Issue by CARocha** [riklaunim/django-ckeditor#43]
Hi, i need install plugin for caption imagen, but i create en my static folder dir ckeditor inside
this structure
.
└── ckeditor
    └── plugins
        ├── dialog
        │   ├── dialogDefinition.js
        │   ├── plugin.js
        │   └── samples
        │       ├── assets
        │       │   └── my_dialog.js
        │       └── dialog.html
        ├── image2
        │   ├── dev
        │   │   ├── assets
        │   │   │   ├── image1.jpg
        │   │   │   └── image2.jpg
        │   │   ├── contents.css
        │   │   └── image2.html
        │   ├── dialogs
        │   │   └── image2.js
        │   ├── icons
        │   │   ├── hidpi
        │   │   │   └── image.png
        │   │   └── image.png
        │   ├── lang
        │   │   ├── af.js
        │   │   ├── ar.js
        │   │   ├── bg.js
        │   │   ├── bn.js
        │   │   ├── bs.js
        │   │   ├── ca.js
        │   │   ├── cs.js
        │   │   ├── cy.js
        │   │   ├── da.js
        │   │   ├── de.js
        │   │   ├── el.js
        │   │   ├── en-au.js
        │   │   ├── en-ca.js
        │   │   ├── en-gb.js
        │   │   ├── en.js
        │   │   ├── eo.js
        │   │   ├── es.js
        │   │   ├── et.js
        │   │   ├── eu.js
        │   │   ├── fa.js
        │   │   ├── fi.js
        │   │   ├── fo.js
        │   │   ├── fr-ca.js
        │   │   ├── fr.js
        │   │   ├── gl.js
        │   │   ├── gu.js
        │   │   ├── he.js
        │   │   ├── hi.js
        │   │   ├── hr.js
        │   │   ├── hu.js
        │   │   ├── id.js
        │   │   ├── is.js
        │   │   ├── it.js
        │   │   ├── ja.js
        │   │   ├── ka.js
        │   │   ├── km.js
        │   │   ├── ko.js
        │   │   ├── ku.js
        │   │   ├── lt.js
        │   │   ├── lv.js
        │   │   ├── mk.js
        │   │   ├── mn.js
        │   │   ├── ms.js
        │   │   ├── nb.js
        │   │   ├── nl.js
        │   │   ├── no.js
        │   │   ├── pl.js
        │   │   ├── pt-br.js
        │   │   ├── pt.js
        │   │   ├── ro.js
        │   │   ├── ru.js
        │   │   ├── si.js
        │   │   ├── sk.js
        │   │   ├── sl.js
        │   │   ├── sq.js
        │   │   ├── sr.js
        │   │   ├── sr-latn.js
        │   │   ├── sv.js
        │   │   ├── th.js
        │   │   ├── tr.js
        │   │   ├── tt.js
        │   │   ├── ug.js
        │   │   ├── uk.js
        │   │   ├── vi.js
        │   │   ├── zh-cn.js
        │   │   └── zh.js
        │   ├── plugin.js
        │   └── samples
        │       ├── assets
        │       │   ├── image1.jpg
        │       │   └── image2.jpg
        │       └── image2.html
        ├── widget
        │   ├── images
        │   │   └── handle.png
        │   ├── lang
        │   │   ├── ar.js
        │   │   ├── ca.js
        │   │   ├── cs.js
        │   │   ├── cy.js
        │   │   ├── de.js
        │   │   ├── el.js
        │   │   ├── en-gb.js
        │   │   ├── en.js
        │   │   ├── eo.js
        │   │   ├── es.js
        │   │   ├── fa.js
        │   │   ├── fi.js
        │   │   ├── fr.js
        │   │   ├── gl.js
        │   │   ├── he.js
        │   │   ├── hr.js
        │   │   ├── hu.js
        │   │   ├── it.js
        │   │   ├── ja.js
        │   │   ├── km.js
        │   │   ├── ko.js
        │   │   ├── nb.js
        │   │   ├── nl.js
        │   │   ├── no.js
        │   │   ├── pl.js
        │   │   ├── pt-br.js
        │   │   ├── pt.js
        │   │   ├── ru.js
        │   │   ├── sl.js
        │   │   ├── sv.js
        │   │   ├── tt.js
        │   │   ├── uk.js
        │   │   ├── vi.js
        │   │   ├── zh-cn.js
        │   │   └── zh.js
        │   └── plugin.js
        └── youtube
            ├── images
            │   └── icon.png
            ├── lang
            │   ├── ar.js
            │   ├── de.js
            │   ├── en.js
            │   ├── fr.js
            │   ├── hu.js
            │   ├── it.js
            │   ├── ja.js
            │   ├── nl.js
            │   ├── pl.js
            │   ├── pt.js
            │   ├── ru.js
            │   ├── tr.js
            │   └── vi.js
            └── plugin.js

but i find in ckeditor but but I do not see the plugins,
I need to activate! 
which is the best way?

thank

**Comment by riklaunim** [comment]
You will probably have to add it to the editor config via CKEDITOR_CONFIGS. Can't tell how exactly it would work. If that isn't a solution then maybe some custom JavaScript?

**Comment by CARocha** [comment]
Hi @riklaunim 
the ckedito_config this is my settings.py

#ckeditor
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': [
    { 'name': 'document', 'groups': [ 'mode', 'document', 'doctools' ], 'items': [ 'Source', '-', 'Save', 'NewPage', 'Preview', 'Print', '-', 'Templates' ] },
    { 'name': 'clipboard', 'groups': [ 'clipboard', 'undo' ], 'items': [ 'Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo' ] },
    { 'name': 'editing', 'groups': [ 'find', 'selection', 'spellchecker' ], 'items': [ 'Find', 'Replace', '-', 'SelectAll', '-', 'Scayt' ] },
    { 'name': 'forms', 'items': [ 'Form', 'Checkbox', 'Radio', 'TextField', 'Textarea', 'Select', 'Button', 'ImageButton', 'HiddenField' ] },
    '/',
    { 'name': 'basicstyles', 'groups': [ 'basicstyles', 'cleanup' ], 'items': [ 'Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat' ] },
    { 'name': 'paragraph', 'groups': [ 'list', 'indent', 'blocks', 'align', 'bidi' ], 'items': [ 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'BidiLtr', 'BidiRtl', 'Language' ] },
    { 'name': 'links', 'items': [ 'Link', 'Unlink', 'Anchor' ] },
    { 'name': 'insert', 'items': [ 'Image', 'Flash', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'PageBreak', 'Iframe' ] },
    '/',
    { 'name': 'styles', 'items': [ 'Styles', 'Format', 'Font', 'FontSize' ] },
    { 'name': 'colors', 'items': [ 'TextColor', 'BGColor' ] },
    { 'name': 'tools', 'items': [ 'Maximize', 'ShowBlocks' ] },
    { 'name': 'others', 'items': [ '-' ] },
        ],
    },
}

CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_IMAGE_BACKEND = "pillow"

Where should I place the plugins?

thank

**Comment by CARocha** [comment]
Hi, i see need put extraPlugins: namePlugins but not working, see my new setting
CKEDITOR_CONFIGS = {
    'default': {
        'extraPlugins': 'youtube',
        'toolbar': [
            { 'name': 'document', 'groups': [ 'mode', 'document', 'doctools' ], 'items': [ 'Source', '-', 'Save', 'NewPage', 'Preview', 'Print', '-', 'Templates' ] },
            { 'name': 'clipboard', 'groups': [ 'clipboard', 'undo' ], 'items': [ 'Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo' ] },
            { 'name': 'editing', 'groups': [ 'find', 'selection', 'spellchecker' ], 'items': [ 'Find', 'Replace', '-', 'SelectAll', '-', 'Scayt' ] },
            { 'name': 'forms', 'items': [ 'Form', 'Checkbox', 'Radio', 'TextField', 'Textarea', 'Select', 'Button', 'ImageButton', 'HiddenField' ] },
            '/',
            { 'name': 'basicstyles', 'groups': [ 'basicstyles', 'cleanup' ], 'items': [ 'Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat' ] },
            { 'name': 'paragraph', 'groups': [ 'list', 'indent', 'blocks', 'align', 'bidi' ], 'items': [ 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'BidiLtr', 'BidiRtl', 'Language' ] },
            { 'name': 'links', 'items': [ 'Link', 'Unlink', 'Anchor' ] },
            { 'name': 'insert', 'items': [ 'Image', 'Flash', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'PageBreak', 'Iframe' ] },
            '/',
            { 'name': 'styles', 'items': [ 'Styles', 'Format', 'Font', 'FontSize' ] },
            { 'name': 'colors', 'items': [ 'TextColor', 'BGColor' ] },
            { 'name': 'tools', 'items': [ 'Maximize', 'ShowBlocks', ] },
            { 'name': 'others', 'items': [ '-' ] },
        ],
    },
}

but, not working no appears the button for youtube. or any plugins install :(

**Comment by riklaunim** [comment]
Check the JavaScript that is generated on the web page. Compare it with the correct one from a demo where the plugin works - that will reveal the problem :)

**Comment by CARocha** [comment]
Thx @riklaunim now working very well :)
