### ISSUE TITLE
image upload problem

### ISSUE THREAD

**Issue by kuyucakli** [riklaunim/django-ckeditor#48]
Hi, 
I have set my media path as :
MEDIA_ROOT = '/home/gumuskaya/webapps/uploads_gizem_web/'
CKEDITOR_UPLOAD_PATH = MEDIA_ROOT
CKEDITOR_UPLOAD_PREFIX = '/uploads/'
CKEDITOR_MEDIA_PREFIX = '/uploads'

MEDIA_URL = '/uploads/'

Image is uploaded but it gets wrong path when serving... The path must be   /uploads/image_file...
but i get /home/gumuskaya/webapps/uploads_gizem_web/image_file.

Is there something that i am doing wrong?

**Comment by riklaunim** [comment]
CKEDITOR_UPLOAD_PATH should not be absolute. Shold be relative against MEDIA_ROOT.
