### ISSUE TITLE
Widget style attribute breaks layout

### ISSUE THREAD

**Issue by freudenberg** [riklaunim/django-ckeditor#57]
After updating from 4.2.8 to the latest 4.4.x release the widget appears indented. The widget's html has a div with style="margin-left: 106px". I am using CKEditorWidget in a non-admin view.

**Comment by riklaunim** [comment]
there is already a fix on master for that.

**Comment by riklaunim** [comment]
new version of django-ckeditor released with all recent inline fixes.

**Comment by SalahAdDin** [comment]
Wich fixes?

**Comment by riklaunim** [comment]
check commits at https://github.com/shaunsephton/django-ckeditor
