### ISSUE TITLE
when i try to upload an image by admin , it has the csrf problem and upload failed.

### ISSUE THREAD

**Issue by zsluedem** [riklaunim/django-ckeditor#61]
below is my urls.py
`
urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', 'article.views.home'),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]
`

below is the settings
`
MEDIA_ROOT = '/home/sisi/webblog/media/'

MEDIA_URL = '/media/'

STATIC_URL = '/static/'

STATIC_ROOT = '/home/sisi/webblog/static'
# ckeditor settings

CKEDITOR_JQUERY_URL = '//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js'
CKEDITOR_UPLOAD_PATH = 'uploads/'
CKEDITOR_IMAGE_BACKEND = 'pillow'
`

where is the problem. how can i fix it . I want to build my own blog. and use the admin to write the blog.

**Comment by riklaunim** [comment]
What is the exact error message?

**Comment by riklaunim** [comment]
and use https://github.com/django-ckeditor/django-ckeditor not this old version/fort

**Comment by zsluedem** [comment]
Forbidden (403)
CSRF verification failed. Request aborted.
Help
Reason given for failure:
    CSRF token missing or incorrect.

In general, this can occur when there is a genuine Cross Site Request Forgery, or when Django's CSRF mechanism has not been used correctly. For POST forms, you need to ensure:
Your browser is accepting cookies.
The view function passes a request to the template's render method.
In the template, there is a {% csrf_token %} template tag inside each POST form that targets an internal URL.
If you are not using CsrfViewMiddleware, then you must use csrf_protect on any views that use the csrf_token template tag, as well as those that accept the POST data.
You're seeing the help section of this page because you have DEBUG = True in your Django settings file. Change that to False, and only the initial error message will be displayed.
You can customize this page using the CSRF_FAILURE_VIEW setting.
################################################################
this is the error message~! I don't know why~! I set up everything as the demo does.
